apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  namespace: voting-app
  labels:
    name: postgres-config-map
    app: demo-voting-app
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PGDATA: /var/lib/postgresql/data/k8s
  POSTGRES_HOST_AUTH_METHOD: trust