apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webpage
  namespace: ns-workshop-public
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service:
      name: svc-webpage
      port:
        number: 80
  rules:
  - host: webserver.192.168.64.2.nip.io #everba1e.kubelabs.tk # nombre del host ó dominio
    http:
      paths:
      - path: / # por ejemplo /home se vería así en la página: http://mipagina.com/home
        pathType: Prefix
        backend:
          service:
            name: svc-webpage # nombre del service y el puerto donde escucha
            port:
              number: 80
      #- path: /graphql # por ejemplo /home se vería así en la página: http://mipagina.com/home
      #  pathType: Prefix
      #  backend:
      #    service:
      #      name: svc-websocket # nombre del service y el puerto donde escucha
      #      port:
      #        number: 3001

  #- host: www.everba1e.kubelabs.tk
   # http:
    #  paths:
     # - path: /
      #  pathType: Prefix
       # backend:
        #  service:
         #   name: svc-webpage
          #  port:
           #   number: 80