apiVersion: apps/v1
kind: Deployment

metadata:
  name: public-api-deployment
  namespace: ns-workshop-public
  labels:
    app: public-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public-api
  template:
    metadata:
      name: public-api
      labels:
        app: public-api
    spec:
      containers:
        - name: public-api
          image: cachac/kubelabs_publicapi:1.0.1
          ports:
            - containerPort: 3000
              name: public-api
            - containerPort: 3080
              name: healthcheck
          
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5

          envFrom:
            - configMapRef:
                name: private-api-conf
          
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi