apiVersion: v1
kind: Service
metadata:
  name: svc-private-api
  namespace: ns-workshop-private
spec:
  type: ClusterIP
  selector:
    app: private-api
  ports:
    - port: 3002
      targetPort: 3002