apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting-app
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 6379 # Conectamos el puerto 6379 del pod con el 6379 del contenedor
      targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app