apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: voting-app
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort # Tipo de Service
  ports:
    - port: 80 # Puerto donde se conecta el servicio
      targetPort: 80 # Puerto destino del pod
      nodePort: 30000 # Puerto usado para acceder externamente
  selector: # Deben coincidir con los labels de los pod
    name: voting-app-pod
    app: demo-voting-app
